version: "3.5"
services:
  #MySQL Service
  db:
    image: mysql:5.7
    environment:
        MYSQL_ROOT_PASSWORD: NOT_SECURE_CHANGE
        MYSQL_DATABASE: muradb
    volumes:
        - db_data:/var/lib/mysql
    ports:
        - "55556:3306"

  #Mura Service
  mura:
    depends_on:
      - db
    build: ./Mura
    environment:
      MURA_ADMIN_USERNAME: admin
      MURA_ADMIN_PASSWORD: admin
      MURA_ADMINEMAIL: example@localhost.com
      MURA_APPRELOADKEY: appreload
      MURA_DATASOURCE: muradb
      MURA_DATABASE: muradb
      MURA_DBTYPE: mysql
      MURA_DBUSERNAME: root
      MURA_DBPASSWORD: NOT_SECURE_CHANGE
      MURA_DBHOST: db
      MURA_DBPORT: 3306
      MURA_SITEIDINURLS: "false"
      MURA_INDEXFILEINURLS: "false"
      MURA_EXTERNALCONFIG: http://vue:8080/mura.config.json
    volumes:
        - ./Mura/app/config:/var/www/config
        - ./Mura/app/plugins:/var/www/plugins
        - ./Mura/app/themes:/var/www/themes
        - ./Mura/app/etc:/var/www/etc
        - ./Mura/app/sites:/var/www/sites
    ports:
        - "8888:8888"
    healthcheck:
      disable: true

  #Node Service
  vue:
    depends_on:
      - mura
    build: ./Vue
    command: npm run serve
    volumes:
      - ./Vue:/usr/app/
      -  node_modules:/usr/app/node_modules
    ports:
      - "8080:8080"

volumes:
  db_data:
  node_modules:
